In [56]:
import joblib
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [57]:
path = "../out/final/"
t1_classifier = joblib.load(path + 't1_classifier.joblib.z')
t2_classifier = joblib.load(path + 't2_classifier.joblib.z')
t3bc_classifier = joblib.load(path + 't3bc_classifier.joblib.z')
t3cc_classifier = joblib.load(path + 't3cc_classifier.joblib.z')
t3lp_classifier = joblib.load(path + 't3lp_classifier.joblib.z')
t3ovr_classifier = joblib.load(path + 't3ovr_classifier.joblib.z')

In [58]:
test_df = pd.read_csv("../res/test_final.csv")
test_df.head()

text  HATE  NOT  OFFN  PRFN  \
0  its about time blacks realised the women who s...     1    0     0     1   
1  the islamic and sharia controlled middle easte...     0    0     1     1   
2  so now you are calling yourself whoever agrees...     0    0     1     1   
3  a million thumbs up we need museums of victims...     0    1     0     1   
4  these your kike bosses too feldman is cernovic...     1    0     0     1   

   Race  Religion  Gender  Other  None  
0     0         1       0      0     0  
1     0         1       0      0     0  
2     0         0       0      0     1  
3     1         0       0      0     0  
4     0         1       0      0     0

In [59]:
x_t1_classifier = t1_classifier.predict(test_df["text"])
y_t1_classifier = test_df[["HATE","NOT","OFFN"]]

accuracy_t1_classifier = accuracy_score(x_t1_classifier, y_t1_classifier)*100
accuracy_t1_classifier

51.88908145580589

In [60]:
#x_t2_classifier = t2_classifier.predict(test_df["text"])
#y_t2_classifier = test_df[["PRFN"]]

#accuracy_t2_classifier = accuracy_score(x_t2_classifier, y_t2_classifier)*100
#accuracy_t2_classifier

In [61]:
#x_t3bc_classifier = t3bc_classifier.predict(test_df["text"])
#y_t3bc_classifier = test_df[["Race","Religion","Gender","Other","None"]]

#accuracy_t3bc_classifier = accuracy_score(x_t3bc_classifier, y_t3bc_classifier)*100
#accuracy_t3bc_classifier

54.9740034662045

In [62]:
x_t3cc_classifier = t3cc_classifier.predict(test_df["text"])
y_tt3cc_classifier = test_df[["Race","Religion","Gender","Other","None"]]

accuracy_t3cc_classifier = accuracy_score(x_t3cc_classifier, y_tt3cc_classifier)*100
accuracy_t3cc_classifier

48.56152512998267

In [63]:
x_t3lp_classifier = t3lp_classifier.predict(test_df["text"])
y_t3lp_classifier = test_df[["Race","Religion","Gender","Other","None"]]

accuracy_t3lp_classifier = accuracy_score(x_t3lp_classifier, y_t3lp_classifier)*100
accuracy_t3lp_classifier

48.07625649913344

In [64]:
x_t3ovr_classifier = t3ovr_classifier.predict(test_df["text"])
y_t3ovr_classifier = test_df[["Race","Religion","Gender","Other","None"]]

accuracy_t3ovr_classifier = accuracy_score(x_t3ovr_classifier, y_t3ovr_classifier)*100
accuracy_t3ovr_classifier

54.9740034662045

In [65]:
# Define a dictionary containing accuracy data
model_data = {'Models':['t1_classifier', 't3cc_classifier', 't3lp_classifier', 't3ovr_classifier'],
        'Accuracy Score':[accuracy_t1_classifier, accuracy_t3cc_classifier, accuracy_t3lp_classifier, accuracy_t3ovr_classifier]}
  
# Convert the dictionary into DataFrame 
Accuracy_df = pd.DataFrame(model_data)
  
# select two columns
Accuracy_df = (Accuracy_df[['Models', 'Accuracy Score']])
Accuracy_df

Models  Accuracy Score
0     t1_classifier       51.889081
1   t3cc_classifier       48.561525
2   t3lp_classifier       48.076256
3  t3ovr_classifier       54.974003

In [66]:
from sklearn.metrics import multilabel_confusion_matrix
#Confusion Matrix
confusion_matrix_t1 = (multilabel_confusion_matrix(x_t1_classifier, y_t1_classifier))
confusion_matrix_t3cc = (multilabel_confusion_matrix(x_t3cc_classifier, y_tt3cc_classifier))
confusion_matrix_t3lp = (multilabel_confusion_matrix(x_t3lp_classifier, y_t3lp_classifier))
confusion_matrix_t3ovr = (multilabel_confusion_matrix(x_t3ovr_classifier, y_t3ovr_classifier))


In [67]:
print("t1_calssifier confusion matrix:\n",confusion_matrix_t1,"\n")
print("tt3cc_calssifier confusion matrix:\n",confusion_matrix_t3cc,"\n")
print("t3lp_calssifier confusion matrix:\n",confusion_matrix_t3lp,"\n")
print("t3ovr_calssifier confusion matrix:\n",confusion_matrix_t3ovr,"\n")

t1_calssifier confusion matrix:
 [[[1847  368]
  [ 117  553]]

 [[1392  372]
  [ 358  763]]

 [[1937  618]
  [ 119  211]]] 

tt3cc_calssifier confusion matrix:
 [[[2140  400]
  [  35  310]]

 [[2285  414]
  [  12  174]]

 [[2394  376]
  [  29   86]]

 [[2620  219]
  [  12   34]]

 [[ 617   62]
  [1308  898]]] 

t3lp_calssifier confusion matrix:
 [[[2095  390]
  [  80  320]]

 [[2277  423]
  [  20  165]]

 [[2381  376]
  [  42   86]]

 [[2621  222]
  [  11   31]]

 [[ 670   85]
  [1255  875]]] 

t3ovr_calssifier confusion matrix:
 [[[2126  232]
  [  49  478]]

 [[2219  146]
  [  78  442]]

 [[2327  205]
  [  96  257]]

 [[2597  173]
  [  35   80]]

 [[1628  438]
  [ 297  522]]] 



In [68]:
from sklearn.metrics import classification_report

t1_target_names = ["HATE","NOT","OFFN"]
t3cc_target_names = ["Race","Religion","Gender","Other","None"]
t3lp_target_names = ["Race","Religion","Gender","Other","None"]
t3ovr_target_names = ["Race","Religion","Gender","Other","None"]

In [ ]:
t1_classification_report = (classification_report(x_t1_classifier, y_t1_classifier,target_names=t1_target_names))
t3cc_classification_report = (classification_report(x_t3cc_classifier, y_tt3cc_classifier, target_names=t3cc_target_names))
t3lp_classification_report = (classification_report(x_t3lp_classifier, y_t3lp_classifier, target_names=t3lp_target_names))
t3ovr_classification_report = (classification_report(x_t3ovr_classifier, y_t3ovr_classifier, target_names=t3ovr_target_names))

In [70]:
print("t1 classification report: \n",t1_classification_report,"\n")
print("t3cc classification report: \n",t3cc_classification_report,"\n")
print("t3lp classification report: \n",t3lp_classification_report,"\n")
print("t3ovr classification report: \n",t3ovr_classification_report,"\n")

t1 classification report: 
               precision    recall  f1-score   support

        HATE       0.60      0.83      0.70       670
         NOT       0.67      0.68      0.68      1121
        OFFN       0.25      0.64      0.36       330

   micro avg       0.53      0.72      0.61      2121
   macro avg       0.51      0.72      0.58      2121
weighted avg       0.58      0.72      0.63      2121
 samples avg       0.53      0.52      0.53      2121
 

t3cc classification report: 
               precision    recall  f1-score   support

        Race       0.44      0.90      0.59       345
    Religion       0.30      0.94      0.45       186
      Gender       0.19      0.75      0.30       115
       Other       0.13      0.74      0.23        46
        None       0.94      0.41      0.57      2206

   micro avg       0.51      0.52      0.51      2898
   macro avg       0.40      0.75      0.43      2898
weighted avg       0.79      0.52      0.55      2898
 samples avg     